import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API='http://localhost:8080';
const request=async(path,options={})=>{const response=await fetch(API+path,options);if(!response.ok)throw new Error(`Request failed (${response.status})`);return response.status===204?null:response.json()};
const json=body=>({headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});

function App(){
 const [products,setProducts]=useState([]),[prices,setPrices]=useState([]),[reorders,setReorders]=useState([]),[journal,setJournal]=useState([]),[system,setSystem]=useState(null);
 const [busy,setBusy]=useState(''),[category,setCategory]=useState('ALL'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[updatedAt,setUpdatedAt]=useState(null),[showJournal,setShowJournal]=useState(false),[notices,setNotices]=useState([]);
 const previousProducts=useRef(new Map()),previousSuggestions=useRef(new Set()),inFlight=useRef(new Set());
 const notify=(message,level='info')=>{const id=crypto.randomUUID();setNotices(current=>[...current,{id,message,level}].slice(-5));setTimeout(()=>setNotices(current=>current.filter(item=>item.id!==id)),7000)};
 const load=async(initial=false)=>{if(initial)setLoading(true);try{const [catalog,pricing,reorder,acceptedPrices,rejectedPrices,acceptedReorders,rejectedReorders,status]=await Promise.all([request('/products'),request('/pricing-suggestions'),request('/reorder-suggestions'),request('/pricing-suggestions?status=ACCEPTED'),request('/pricing-suggestions?status=REJECTED'),request('/reorder-suggestions?status=ACCEPTED'),request('/reorder-suggestions?status=REJECTED'),request('/system/status')]);const old=previousProducts.current;const firstLoad=old.size===0;catalog.forEach(product=>{const before=old.get(product.id);if(before&&before.stockLevel>product.stockLevel){notify(`${product.name}: sale recorded. Stock is now ${product.stockLevel}.`,'info');if(before.stockLevel>=product.reorderThreshold&&product.stockLevel<product.reorderThreshold)notify(`${product.name}: low-stock threshold reached (${product.stockLevel}/${product.reorderThreshold}).`,'warning')}else if(firstLoad&&product.stockLevel<product.reorderThreshold)notify(`${product.name}: currently below reorder threshold (${product.stockLevel}/${product.reorderThreshold}).`,'warning')});previousProducts.current=new Map(catalog.map(product=>[product.id,product]));const fresh=[...pricing,...reorder].filter(item=>!previousSuggestions.current.has(item.id));if(!firstLoad)fresh.forEach(item=>notify(`New ${item.recommendedPrice?'price':'reorder'} recommendation for ${item.product.name}.`,'success'));previousSuggestions.current=new Set([...pricing,...reorder].map(item=>item.id));setProducts(catalog);setPrices(pricing);setReorders(reorder);setSystem(status);setJournal([...acceptedPrices,...rejectedPrices,...acceptedReorders,...rejectedReorders].sort((a,b)=>new Date(b.decidedAt||b.createdAt)-new Date(a.decidedAt||a.createdAt)));setError('');setUpdatedAt(new Date())}catch{setError('The console cannot reach the API. Start the backend, then refresh.')}finally{if(initial)setLoading(false)}};
 useEffect(()=>{load(true);const interval=setInterval(()=>load(),2500);return()=>clearInterval(interval)},[]);
 const visibleProducts=useMemo(()=>{const list=category==='ALL'?products:products.filter(p=>p.category===category);return [...list].sort((a,b)=>(a.stockLevel/Math.max(1,a.demandVelocity))-(b.stockLevel/Math.max(1,b.demandVelocity)))},[products,category]);
 const action=async(key,fn)=>{if(inFlight.current.has(key))return;inFlight.current.add(key);setBusy(key);try{await fn();await new Promise(r=>setTimeout(r,350));await load()}catch{setError('That action could not be saved. Please try again.')}finally{inFlight.current.delete(key);setBusy('')}};
 const sale=p=>action(p.id,()=>request(`/products/${p.id}/orders`,{method:'POST',...json({quantity:1})}));
 const manual=p=>action(`manual-${p.id}`,()=>request(`/products/${p.id}/suggest-pricing`,{method:'POST'}));
 const decide=(type,id,status)=>action(id,()=>request(`/${type}-suggestions/${id}`,{method:'PATCH',...json({status})}));
 const low=products.filter(p=>p.stockLevel<p.reorderThreshold).length;
 return <main>
  <header><div><p className="eyebrow">STOCKPULSE / MERCHANDISING CONSOLE</p><h1>Inventory signals,<br/><i>human decisions.</i></h1><p className="sub">Stock and demand events create safe pricing and reorder advice. Merchandisers approve every live change.</p><div className="mode-strip"><span className={system?.activeStrategy==='AI'?'mode-ai':'mode-rule'}>AI advisor: {system?.activeStrategy==='AI'&&system?.aiGatewayConfigured?`ON · ${system.model}`:'rule fallback'}</span><span className="mode-human">Human approval: REQUIRED</span></div></div><div className="live"><b>● LIVE</b><span>{updatedAt?`Updated ${updatedAt.toLocaleTimeString()}`:'Connecting…'}</span><button className="text-button" onClick={()=>load()} aria-label="Refresh console">Refresh</button></div></header>
  {error&&<div className="notice" role="alert">{error}<button onClick={()=>load(true)}>Retry</button></div>}<div className="toast-stack" aria-live="polite">{notices.map(item=><div className={`toast ${item.level}`} key={item.id}>{item.message}<button aria-label="Dismiss notification" onClick={()=>setNotices(current=>current.filter(note=>note.id!==item.id))}>×</button></div>)}</div>
  <section className="metrics"><Metric n={products.length} l="Products monitored"/><Metric n={low} l="Below threshold"/><Metric n={prices.length+reorders.length} l="Pending decisions"/><Metric n={journal.length} l="Decision journal"/></section>
  <section><div className="title controls"><div><p className="eyebrow">CATALOG BOARD</p><h2>Inventory at a glance</h2></div><label>Category <select value={category} onChange={e=>setCategory(e.target.value)}><option value="ALL">All categories</option><option value="ELECTRONICS">Electronics</option><option value="APPAREL">Apparel</option><option value="HOME">Home</option></select></label></div>
  {loading?<p className="empty">Loading catalog…</p>:<div className="products scroll-board">{visibleProducts.map(p=><Product key={p.id} product={p} busy={busy} onSale={sale} onManual={manual}/>)}</div>}</section>
  <section className="queue"><div className="title"><p className="eyebrow">HUMAN CHECKPOINT</p><h2>Recommendation queue</h2><p className="queue-help">Scroll to review all decisions. A suggestion remains pending until it is accepted or rejected.</p></div>{!prices.length&&!reorders.length&&<p className="empty">No pending recommendations. Simulate a sale on a low-stock product or request advice manually.</p>}<div className="cards scroll-queue">{prices.map(s=><Suggestion key={s.id} type="PRICE" trigger={s.triggerReason} title={s.product.name} detail={`$${s.currentPrice} → $${s.recommendedPrice} · ${s.direction}`} impact={`Commercial impact: ${s.direction==='HOLD'?'no price change':`${s.direction==='INCREASE'?'+':'-'}$${Math.abs(s.recommendedPrice-s.currentPrice).toFixed(2)} (${Math.abs((s.recommendedPrice/s.currentPrice-1)*100).toFixed(1)}%)`}`} source={s.source} reason={s.reasoning} confidence={s.confidence} on={status=>decide('pricing',s.id,status)} busy={busy===s.id}/>) }{reorders.map(s=><Suggestion key={s.id} type="REORDER" trigger={s.triggerReason} title={s.product.name} detail={`${s.currentStock} units now → order ${s.recommendedQuantity} units · ${s.suggestedLeadTimeDays} day lead`} impact={`Coverage after reorder: ${coverage(s.currentStock+s.recommendedQuantity,s.product.demandVelocity)}`} source={s.source} reason={s.reasoning} confidence={s.confidence} on={status=>decide('reorder',s.id,status)} busy={busy===s.id}/>)}</div></section>
  <section className="journal"><div className="title controls"><div><p className="eyebrow">DECISION JOURNAL</p><h2>Approval trail</h2></div><button className="secondary" onClick={()=>setShowJournal(!showJournal)}>{showJournal?'Hide history':'Show history'}</button></div>{showJournal&&<div className="journal-list">{journal.length?journal.slice(0,20).map(item=><div key={item.id} className="journal-item"><span className={item.recommendedPrice?'orange tag':'teal tag'}>{item.recommendedPrice?'PRICE':'REORDER'}</span><b>{item.product.name}</b><span className={item.status==='ACCEPTED'?'accepted':'rejected-status'}>{item.status}</span><small>{item.source||'RULE ENGINE'} · {item.triggerReason.replace('_',' ')} · decided {new Date(item.decidedAt||item.createdAt).toLocaleString()}</small></div>):<p className="empty">No decisions have been made yet.</p>}</div>}</section>
 </main>;
}
const Metric=({n,l})=><div><b>{n}</b><span>{l}</span></div>;
const coverage=(stock,velocity)=>velocity>0?`${(stock/velocity).toFixed(1)} days of stock`:'No recent velocity';
function Product({product:p,busy,onSale,onManual}){const ratio=p.reorderThreshold?Math.min(1,p.stockLevel/p.reorderThreshold):1;const heat=ratio===0?'empty-stock':ratio<1?'low-stock':ratio<1.5?'watch-stock':'healthy-stock';return <article className={`product ${heat}`}><div className="row"><span className="tag">{p.category}</span><span className={p.stockLevel<p.reorderThreshold?'risk':'ok'}>{p.stockLevel===0?'OUT OF STOCK':p.stockLevel<p.reorderThreshold?'LOW STOCK':p.status}</span></div><h3>{p.name}</h3><p className="sku">{p.sku}</p><div className="numbers"><div><b>${p.currentPrice}</b><small>live price</small></div><div><b>{p.stockLevel}</b><small>stock / threshold {p.reorderThreshold}</small></div><div><b>{p.demandVelocity}</b><small>orders, last 24h</small></div></div><p className="runway">Stock runway: <b>{coverage(p.stockLevel,p.demandVelocity)}</b></p><div className="stock-meter" aria-label={`${p.stockLevel} stock units, threshold ${p.reorderThreshold}`}><i style={{width:`${Math.min(100,ratio*100)}%`}}/></div><div className="actions"><button disabled={busy===p.id||p.stockLevel===0} onClick={()=>onSale(p)}>{busy===p.id?'Recording…':'Simulate sale'}</button><button className="secondary" disabled={busy===`manual-${p.id}`} onClick={()=>onManual(p)}>{busy===`manual-${p.id}`?'Requesting…':'Request advice'}</button></div></article>}
function Suggestion({type,trigger,title,detail,impact,source,reason,confidence,on,busy}){const triggerLabel=trigger==='MANUAL'?'MANUAL':'AUTO';return <article className="suggestion"><div className="row"><span className={type==='PRICE'?'orange tag':'teal tag'}>{type}</span><span className="trigger">{triggerLabel} · {trigger.replace('_',' ')}</span></div><h3>{title}</h3><strong>{detail}</strong><p className="impact">{impact}</p><p className="source">Source: {source||'RULE ENGINE'}</p><p>“{reason}”</p><div className="confidence"><span>Confidence</span><div><i style={{width:`${confidence*100}%`}}/></div><b>{Math.round(confidence*100)}%</b></div><div className="actions"><button className="accept" disabled={busy} onClick={()=>on('ACCEPTED')}>Accept</button><button className="reject" disabled={busy} onClick={()=>on('REJECTED')}>Reject</button></div></article>}
createRoot(document.getElementById('root')).render(<App/>);
